### ISSUE TITLE
Upgrade from v0.1.0 to v0.2.1

### ISSUE THREAD

**Issue by kacnje** [markerikson/joplin-plugin-vscode-style-search#5]
Any suggestion how to upgrade from 0.1.0 to 0.2.1? 
If I click on UPDATE button (in Joplin -> Settings -> Plugins), it doesn't find an upgrade. 
I use search on Joplin Plugins website, it shows 0.1.0 so this also doesn't work.

**Comment by markerikson** [comment]
Ah, looks like I need to bump the version number in `manifest.json` manually, not just the normal `npm publish` to bump the package number in `package.json`.

Just published 0.2.2. Let me know if that shows up okay!

**Comment by kacnje** [comment]
I can confirm that upgrading now works. 
Tnx. 
Just go on. I'm sure this plugin will be one of the most used after some development.

**Comment by markerikson** [comment]
Glad that worked!

Yeah, I have no idea how to measure usage stats for the plugin. Oh well :)
